project_name: pcba-test
dist: dist

release:
  github:
    owner: TheCacophonyProject
    name: pcba-test
  name_template: '{{.Tag}}'

builds:
- id: pcba-test-cli
  binary: pcba-test-cli
  main: ./cmd/pcba-test-cli
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}
- id: pcba-test-interface
  binary: pcba-test-interface
  main: ./cmd/pcba-test-interface
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}
  hooks:
    pre: packr
    post: packr clean

nfpms:
- vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <coredev@cacophony.org.nz>
  description: Tool for testing PCBA
  license: GPL v3.0
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
