language: go

go:
  - "1.13.x"

script:
  - go vet ./...
  - go test ./...

# Create a release using goreleaser when tests pass and revision is tagged.
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    go: "1.13.x"
